name: Move perf-history file
on:
  push:
    tags:
      - '*'


jobs:
  move:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get tag
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Rename perf-history.csv
        run: |
          mv "perf-history/perf-history.csv" "perf-history/perf-history-${{ steps.get_version.outputs.VERSION }}.csv"
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "Rename perf-history.csv by adding current version"
          add: "*"
          push: origin HEAD:main